// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Api.Streams.Subjects;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NovaLab.ApiClient.Api.Streams
{
    /// <summary>
    /// Builds and executes requests for operations under \api\streams
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class StreamsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The subjects property</summary>
        public global::NovaLab.ApiClient.Api.Streams.Subjects.SubjectsRequestBuilder Subjects
        {
            get => new global::NovaLab.ApiClient.Api.Streams.Subjects.SubjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Streams.StreamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StreamsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/streams", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Streams.StreamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StreamsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/streams", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
