// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NovaLab.ApiClient.Api.Twitch
{
    /// <summary>
    /// Builds and executes requests for operations under \api\twitch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class TwitchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The trackedStreamSubject property</summary>
        public global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder TrackedStreamSubject
        {
            get => new global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TwitchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwitchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TwitchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwitchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch", rawUrl)
        {
        }
    }
}
