ARG DOTNET_RUNTIME=mcr.microsoft.com/dotnet/aspnet:8.0
ARG DOTNET_SDK=mcr.microsoft.com/dotnet/sdk:8.0

# Stage 1: Build the Blazor application
FROM ${DOTNET_SDK} AS build
ARG BUILD_CONFIGURATION=Release

COPY . .
WORKDIR ./src/servers/api/NovaLab.Servers.API
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

WORKDIR ../NovaLab.Servers.API.Tools
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

# Stage 2: Publish the application
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "../NovaLab.Servers.API/NovaLab.Servers.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish/NovaLab.Servers.API /p:UseAppHost=false -p:PublishTrimmed=false && \
    dotnet publish "NovaLab.Servers.API.Tools.csproj" -c $BUILD_CONFIGURATION -o /app/publish/NovaLab.Servers.API.Tools /p:UseAppHost=false -p:PublishTrimmed=false

# Stage 3: Create the runtime image
FROM ${DOTNET_RUNTIME} AS base
WORKDIR /app
COPY --from=publish /app/publish .
COPY tools-api.sh .

RUN chmod +x ./tools-api.sh

EXPOSE 443

ENTRYPOINT ["dotnet", "/app/NovaLab.Servers.API/NovaLab.Servers.API.dll"]