ARG DOTNET_RUNTIME=mcr.microsoft.com/dotnet/aspnet:8.0
ARG DOTNET_SDK=mcr.microsoft.com/dotnet/sdk:8.0

# Stage 1: Build the application
FROM ${DOTNET_SDK} AS build
ARG BUILD_CONFIGURATION=Release

COPY . .

WORKDIR ./src/servers/blazor/NovaLab.Servers.Blazor
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

WORKDIR ../NovaLab.Servers.Blazor.Tools
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

# Stage 2: Publish the application
FROM build AS publish
RUN dotnet publish "../NovaLab.Servers.Blazor/NovaLab.Servers.Blazor.csproj" -c $BUILD_CONFIGURATION -o /app/publish/NovaLab.Servers.Blazor /p:UseAppHost=false -p:PublishTrimmed=false && \
    dotnet publish "NovaLab.Servers.Blazor.Tools.csproj" -c $BUILD_CONFIGURATION -o /app/publish/NovaLab.Servers.Blazor.Tools /p:UseAppHost=false -p:PublishTrimmed=false

# Stage 3: Create the runtime image
FROM ${DOTNET_RUNTIME} AS base
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=publish /app/publish/NovaLab.Servers.Blazor/wwwroot ./wwwroot
COPY tools-blazor.sh .

RUN chmod +x ./tools-blazor.sh

EXPOSE 443

ENTRYPOINT ["dotnet", "/app/NovaLab.Servers.Blazor/NovaLab.Servers.Blazor.dll"]