services:
  novalab-blazor:
    build:
      context: .
      dockerfile: Dockerfile-Blazor
    ports:
      - "9051:443" # HTTPS
    depends_on:
      - novalab-sqlserver
    environment:
      ASPNETCORE_URLS : "https://+:443"
      ASPNETCORE_ENVIRONMENT : "Release"
      RunningInDocker : "true"
      TwitchClientId : ${TwitchClientId}
      TwitchClientSecret : ${TwitchClientSecret}
      DockerDb : "Server=novalab-sqlserver;Database=NovaLabDb;User=sa;Password=${SqlServerSAPassword};TrustServerCertificate=True"
      SslCertLocation : "/root/.aspnet/https/NovaLab.Servers.Blazor.pfx"
      SslCertPassword : ${SslCertPassword}
      ApiUrlRoot : "https://localhost:9052"
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
      - "${USERPROFILE}/.aspnet/https/NovaLab.Servers.Blazor.pfx:/root/.aspnet/https/NovaLab.Servers.Blazor.pfx:ro"
      - "/var/opt/mssql/backups:/backups" # bind to same backup location as the sqlserver
    networks:
      - novalab-net
      
  novalab-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SqlServerSAPassword}
      ACCEPT_EULA: "Y"
    ports:
      - "9050:1433"
    volumes:
      - NovaLabSQLServerVolume:/var/opt/mssql
      - ./backups:/var/opt/mssql/backups
    networks:
      - novalab-net

volumes:
  NovaLabSQLServerVolume:

networks:
  novalab-net:
