services:
  novalab-server:
    build:
      context: .
      dockerfile: Dockerfile-Server
    ports:
      - "9051:443" # HTTPS
    depends_on:
      - sqlserver
      - novalab-api
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_ENVIRONMENT=Release
      - RunningInDocker=true
      - TwitchClientId=${TwitchClientId}
      - TwitchClientSecret=${TwitchClientSecret}
      - DockerDb=Server=sqlserver;Database=NovaLabDb;User=sa;Password=${SqlServerSAPassword};TrustServerCertificate=True
      - SslCertLocation=/root/.aspnet/https/NovaLab.Server.pfx
      - SslCertPassword=${SllCertsPassword}
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
      - "${USERPROFILE}/.aspnet/https/NovaLab.Server.pfx:/root/.aspnet/https/NovaLab.Server.pfx:ro"
    networks:
      - novalab-net
      
  novalab-api:
    build:
      context: .
      dockerfile: Dockerfile-API
    ports:
      - "9052:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_ENVIRONMENT=Release
      - RunningInDocker=true
      - TwitchClientId=${TwitchClientId}
      - TwitchClientSecret=${TwitchClientSecret}
      - DockerDb=Server=sqlserver;Database=NovaLabDb;User=sa;Password=${SqlServerSAPassword};TrustServerCertificate=True
      - SslCertLocation=/root/.aspnet/https/NovaLab.API.pfx
      - SslCertPassword=${SllCertsPassword}
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
      - "${USERPROFILE}/.aspnet/https/NovaLab.API.pfx:/root/.aspnet/https/NovaLab.API.pfx:ro"
      - "/var/opt/mssql/backups:/backups" # bind to same backup location as the sqlserver
    networks:
      - novalab-net
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SqlServerSAPassword}
      ACCEPT_EULA: "Y"
    ports:
      - "9050:1433"
    volumes:
      - NovaLabSQLServerVolume:/var/opt/mssql
      - ./backups:/var/opt/mssql/backups
    networks:
      - novalab-net

volumes:
  NovaLabSQLServerVolume:

networks:
  novalab-net:
