// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Api.Streams.Subjects.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace NovaLab.ApiClient.Api.Streams.Subjects
{
    /// <summary>
    /// Builds and executes requests for operations under \api\streams\subjects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class SubjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NovaLab.ApiClient.api.streams.subjects.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder"/></returns>
        public global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.SubjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/streams/subjects", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.SubjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/streams/subjects", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
