// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NovaLab.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public partial class RefreshTokenResponseDtoIApiResult : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NovaLab.ApiClient.Models.RefreshTokenResponseDto>? Data { get; set; }
#nullable restore
#else
        public List<global::NovaLab.ApiClient.Models.RefreshTokenResponseDto> Data { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.RefreshTokenResponseDtoIApiResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NovaLab.ApiClient.Models.RefreshTokenResponseDtoIApiResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NovaLab.ApiClient.Models.RefreshTokenResponseDtoIApiResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::NovaLab.ApiClient.Models.RefreshTokenResponseDto>(global::NovaLab.ApiClient.Models.RefreshTokenResponseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::NovaLab.ApiClient.Models.RefreshTokenResponseDto>("data", Data);
            writer.WriteStringValue("message", Message);
            writer.WriteIntValue("status", Status);
        }
    }
}
#pragma warning restore CS0618
