// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NovaLab.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public partial class StreamSubjectDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NovaLab.ApiClient.Models.Ulid? Id { get; set; }
#nullable restore
#else
        public global::NovaLab.ApiClient.Models.Ulid Id { get; set; }
#endif
        /// <summary>The novaLabUserId property</summary>
        public Guid? NovaLabUserId { get; set; }
        /// <summary>The twitchBroadcastLanguage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchBroadcastLanguage { get; set; }
#nullable restore
#else
        public string TwitchBroadcastLanguage { get; set; }
#endif
        /// <summary>The twitchGameId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchGameId { get; set; }
#nullable restore
#else
        public string TwitchGameId { get; set; }
#endif
        /// <summary>The twitchGameImageUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchGameImageUrl { get; set; }
#nullable restore
#else
        public string TwitchGameImageUrl { get; set; }
#endif
        /// <summary>The twitchGameName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchGameName { get; set; }
#nullable restore
#else
        public string TwitchGameName { get; set; }
#endif
        /// <summary>The twitchTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TwitchTags { get; set; }
#nullable restore
#else
        public List<string> TwitchTags { get; set; }
#endif
        /// <summary>The twitchTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchTitle { get; set; }
#nullable restore
#else
        public string TwitchTitle { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.StreamSubjectDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NovaLab.ApiClient.Models.StreamSubjectDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NovaLab.ApiClient.Models.StreamSubjectDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetObjectValue<global::NovaLab.ApiClient.Models.Ulid>(global::NovaLab.ApiClient.Models.Ulid.CreateFromDiscriminatorValue); } },
                { "novaLabUserId", n => { NovaLabUserId = n.GetGuidValue(); } },
                { "twitchBroadcastLanguage", n => { TwitchBroadcastLanguage = n.GetStringValue(); } },
                { "twitchGameId", n => { TwitchGameId = n.GetStringValue(); } },
                { "twitchGameImageUrl", n => { TwitchGameImageUrl = n.GetStringValue(); } },
                { "twitchGameName", n => { TwitchGameName = n.GetStringValue(); } },
                { "twitchTags", n => { TwitchTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "twitchTitle", n => { TwitchTitle = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NovaLab.ApiClient.Models.Ulid>("id", Id);
            writer.WriteGuidValue("novaLabUserId", NovaLabUserId);
            writer.WriteStringValue("twitchBroadcastLanguage", TwitchBroadcastLanguage);
            writer.WriteStringValue("twitchGameId", TwitchGameId);
            writer.WriteStringValue("twitchGameImageUrl", TwitchGameImageUrl);
            writer.WriteStringValue("twitchGameName", TwitchGameName);
            writer.WriteCollectionOfPrimitiveValues<string>("twitchTags", TwitchTags);
            writer.WriteStringValue("twitchTitle", TwitchTitle);
        }
    }
}
#pragma warning restore CS0618
