// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NovaLab.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public partial class TrackedStreamSubjectDtoPost : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The novaLabUserId property</summary>
        public Guid? NovaLabUserId { get; set; }
        /// <summary>The twitchBroadcastLanguage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchBroadcastLanguage { get; set; }
#nullable restore
#else
        public string TwitchBroadcastLanguage { get; set; }
#endif
        /// <summary>The twitchGameTitleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchGameTitleName { get; set; }
#nullable restore
#else
        public string TwitchGameTitleName { get; set; }
#endif
        /// <summary>The twitchTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TwitchTags { get; set; }
#nullable restore
#else
        public List<string> TwitchTags { get; set; }
#endif
        /// <summary>The twitchTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwitchTitle { get; set; }
#nullable restore
#else
        public string TwitchTitle { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "novaLabUserId", n => { NovaLabUserId = n.GetGuidValue(); } },
                { "twitchBroadcastLanguage", n => { TwitchBroadcastLanguage = n.GetStringValue(); } },
                { "twitchGameTitleName", n => { TwitchGameTitleName = n.GetStringValue(); } },
                { "twitchTags", n => { TwitchTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "twitchTitle", n => { TwitchTitle = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("novaLabUserId", NovaLabUserId);
            writer.WriteStringValue("twitchBroadcastLanguage", TwitchBroadcastLanguage);
            writer.WriteStringValue("twitchGameTitleName", TwitchGameTitleName);
            writer.WriteCollectionOfPrimitiveValues<string>("twitchTags", TwitchTags);
            writer.WriteStringValue("twitchTitle", TwitchTitle);
        }
    }
}
