// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All;
using NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select;
using NovaLab.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject
{
    /// <summary>
    /// Builds and executes requests for operations under \api\twitch\tracked-stream-subject
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class TrackedStreamSubjectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder All
        {
            get => new global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The select property</summary>
        public global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder Select
        {
            get => new global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrackedStreamSubjectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch/tracked-stream-subject{?subject%2Did*,subjectId*,user%2Did*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrackedStreamSubjectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch/tracked-stream-subject{?subject%2Did*,subjectId*,user%2Did*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.BooleanIApiResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResult">When receiving a 400 status code</exception>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResult">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.BooleanIApiResult?> DeleteAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.BooleanIApiResult> DeleteAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::NovaLab.ApiClient.Models.ApiResult.CreateFromDiscriminatorValue },
                { "500", global::NovaLab.ApiClient.Models.ApiResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.BooleanIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.BooleanIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.IApiResult">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult?> GetAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult> GetAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::NovaLab.ApiClient.Models.IApiResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResult">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult?> PostAsync(global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult> PostAsync(global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::NovaLab.ApiClient.Models.ApiResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        #pragma warning disable CS1591
        public partial class TrackedStreamSubjectRequestBuilderDeleteQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subject%2Did")]
            public string? SubjectId { get; set; }
#nullable restore
#else
            [QueryParameter("subject%2Did")]
            public string SubjectId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        public partial class TrackedStreamSubjectRequestBuilderDeleteRequestConfiguration : RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderDeleteQueryParameters>
        {
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        #pragma warning disable CS1591
        public partial class TrackedStreamSubjectRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subject%2Did")]
            public string? SubjectId { get; set; }
#nullable restore
#else
            [QueryParameter("subject%2Did")]
            public string SubjectId { get; set; }
#endif
            [QueryParameter("user%2Did")]
            public Guid? UserId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        public partial class TrackedStreamSubjectRequestBuilderGetRequestConfiguration : RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderGetQueryParameters>
        {
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        #pragma warning disable CS1591
        public partial class TrackedStreamSubjectRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subjectId")]
            public string? SubjectId { get; set; }
#nullable restore
#else
            [QueryParameter("subjectId")]
            public string SubjectId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        public partial class TrackedStreamSubjectRequestBuilderPostRequestConfiguration : RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.TrackedStreamSubjectRequestBuilder.TrackedStreamSubjectRequestBuilderPostQueryParameters>
        {
        }
    }
}
