// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select
{
    /// <summary>
    /// Builds and executes requests for operations under \api\twitch\tracked-stream-subject\select
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class SelectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SelectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch/tracked-stream-subject/select{?subject%2Did*,user%2Did*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SelectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch/tracked-stream-subject/select{?subject%2Did*,user%2Did*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.BooleanIApiResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResult">When receiving a 400 status code</exception>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResult">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.BooleanIApiResult?> PostAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder.SelectRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.BooleanIApiResult> PostAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder.SelectRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::NovaLab.ApiClient.Models.ApiResult.CreateFromDiscriminatorValue },
                { "500", global::NovaLab.ApiClient.Models.ApiResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.BooleanIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.BooleanIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder.SelectRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder.SelectRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.Select.SelectRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        #pragma warning disable CS1591
        public partial class SelectRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subject%2Did")]
            public string? SubjectId { get; set; }
#nullable restore
#else
            [QueryParameter("subject%2Did")]
            public string SubjectId { get; set; }
#endif
            [QueryParameter("user%2Did")]
            public Guid? UserId { get; set; }
        }
    }
}
