// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Api.Streams.Subjects.Item.Item;
using NovaLab.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NovaLab.ApiClient.Api.Streams.Subjects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\streams\subjects\{userId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the NovaLab.ApiClient.api.streams.subjects.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.Item.Item.WithSubjectItemRequestBuilder"/></returns>
        public global::NovaLab.ApiClient.Api.Streams.Subjects.Item.Item.WithSubjectItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("subjectId", position);
                return new global::NovaLab.ApiClient.Api.Streams.Subjects.Item.Item.WithSubjectItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/streams/subjects/{userId}{?subjectId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/streams/subjects/{userId}{?subjectId*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResultInternalServerError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::NovaLab.ApiClient.Models.ApiResultInternalServerError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.ApiResultBadRequest">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult?> PostAsync(global::NovaLab.ApiClient.Models.StreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult> PostAsync(global::NovaLab.ApiClient.Models.StreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::NovaLab.ApiClient.Models.ApiResultBadRequest.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.StreamSubjectDtoIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::NovaLab.ApiClient.Models.StreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::NovaLab.ApiClient.Models.StreamSubjectDtoPost body, Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder.WithUserItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NovaLab.ApiClient.Api.Streams.Subjects.Item.WithUserItemRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
        #pragma warning disable CS1591
        public partial class WithUserItemRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("subjectId")]
            public string? SubjectId { get; set; }
#nullable restore
#else
            [QueryParameter("subjectId")]
            public string SubjectId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
