// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NovaLab.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All
{
    /// <summary>
    /// Builds and executes requests for operations under \api\twitch\tracked-stream-subject\all
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class AllRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AllRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch/tracked-stream-subject/all{?user%2Did*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AllRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/twitch/tracked-stream-subject/all{?user%2Did*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::NovaLab.ApiClient.Models.IApiResult">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult?> GetAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder.AllRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult> GetAsync(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder.AllRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::NovaLab.ApiClient.Models.IApiResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult>(requestInfo, global::NovaLab.ApiClient.Models.TrackedStreamSubjectDtoIApiResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder.AllRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder.AllRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NovaLab.ApiClient.Api.Twitch.TrackedStreamSubject.All.AllRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        #pragma warning disable CS1591
        public partial class AllRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("user%2Did")]
            public Guid? UserId { get; set; }
        }
    }
}
