/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace NovaLab.ApiClient.Model;

/// <summary>
///     TwitchFollowerGoalDto
/// </summary>
[DataContract(Name = "TwitchFollowerGoalDto")]
public class TwitchFollowerGoalDto : IEquatable<TwitchFollowerGoalDto>, IValidatableObject {
    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchFollowerGoalDto" /> class.
    /// </summary>
    /// <param name="userId">userId.</param>
    /// <param name="goalId">goalId.</param>
    /// <param name="dailyGoalAmount">dailyGoalAmount.</param>
    /// <param name="divider">divider.</param>
    /// <param name="customCssStyling">customCssStyling.</param>
    public TwitchFollowerGoalDto(string userId = default, Guid goalId = default, int dailyGoalAmount = default, string divider = default, string customCssStyling = default) {
        UserId = userId;
        GoalId = goalId;
        DailyGoalAmount = dailyGoalAmount;
        Divider = divider;
        CustomCssStyling = customCssStyling;
    }

    /// <summary>
    ///     Gets or Sets UserId
    /// </summary>
    [DataMember(Name = "userId", EmitDefaultValue = true)]
    public string UserId { get; set; }

    /// <summary>
    ///     Gets or Sets GoalId
    /// </summary>
    [DataMember(Name = "goalId", EmitDefaultValue = false)]
    public Guid GoalId { get; set; }

    /// <summary>
    ///     Gets or Sets DailyGoalAmount
    /// </summary>
    [DataMember(Name = "dailyGoalAmount", EmitDefaultValue = false)]
    public int DailyGoalAmount { get; set; }

    /// <summary>
    ///     Gets or Sets Divider
    /// </summary>
    [DataMember(Name = "divider", EmitDefaultValue = true)]
    public string Divider { get; set; }

    /// <summary>
    ///     Gets or Sets CustomCssStyling
    /// </summary>
    [DataMember(Name = "customCssStyling", EmitDefaultValue = true)]
    public string CustomCssStyling { get; set; }

    /// <summary>
    ///     Returns true if TwitchFollowerGoalDto instances are equal
    /// </summary>
    /// <param name="input">Instance of TwitchFollowerGoalDto to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(TwitchFollowerGoalDto input) {
        if (input == null) {
            return false;
        }
        return
            (
                UserId == input.UserId ||
                UserId != null &&
                UserId.Equals(input.UserId)
            ) &&
            (
                GoalId == input.GoalId ||
                GoalId != null &&
                GoalId.Equals(input.GoalId)
            ) &&
            (
                DailyGoalAmount == input.DailyGoalAmount ||
                DailyGoalAmount.Equals(input.DailyGoalAmount)
            ) &&
            (
                Divider == input.Divider ||
                Divider != null &&
                Divider.Equals(input.Divider)
            ) &&
            (
                CustomCssStyling == input.CustomCssStyling ||
                CustomCssStyling != null &&
                CustomCssStyling.Equals(input.CustomCssStyling)
            );
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext) {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString() {
        var sb = new StringBuilder();
        sb.Append("class TwitchFollowerGoalDto {\n");
        sb.Append("  UserId: ").Append(UserId).Append("\n");
        sb.Append("  GoalId: ").Append(GoalId).Append("\n");
        sb.Append("  DailyGoalAmount: ").Append(DailyGoalAmount).Append("\n");
        sb.Append("  Divider: ").Append(Divider).Append("\n");
        sb.Append("  CustomCssStyling: ").Append(CustomCssStyling).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input) => Equals(input as TwitchFollowerGoalDto);

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode() {
        unchecked// Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (UserId != null) {
                hashCode = hashCode * 59 + UserId.GetHashCode();
            }
            if (GoalId != null) {
                hashCode = hashCode * 59 + GoalId.GetHashCode();
            }
            hashCode = hashCode * 59 + DailyGoalAmount.GetHashCode();
            if (Divider != null) {
                hashCode = hashCode * 59 + Divider.GetHashCode();
            }
            if (CustomCssStyling != null) {
                hashCode = hashCode * 59 + CustomCssStyling.GetHashCode();
            }
            return hashCode;
        }
    }
}
