/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace NovaLab.ApiClient.Model;

/// <summary>
///     TwitchFollowerGoal
/// </summary>
[DataContract(Name = "TwitchFollowerGoal")]
public class TwitchFollowerGoal : IEquatable<TwitchFollowerGoal>, IValidatableObject {
    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchFollowerGoal" /> class.
    /// </summary>
    /// <param name="id">id.</param>
    /// <param name="userId">userId.</param>
    /// <param name="user">user.</param>
    /// <param name="dailyGoal">dailyGoal.</param>
    /// <param name="customCssStyling">customCssStyling.</param>
    public TwitchFollowerGoal(Guid id = default, string userId = default, NovaLabUser user = default, int dailyGoal = default, string customCssStyling = default) {
        Id = id;
        UserId = userId;
        User = user;
        DailyGoal = dailyGoal;
        CustomCssStyling = customCssStyling;
    }

    /// <summary>
    ///     Gets or Sets Id
    /// </summary>
    [DataMember(Name = "id", EmitDefaultValue = false)]
    public Guid Id { get; set; }

    /// <summary>
    ///     Gets or Sets UserId
    /// </summary>
    [DataMember(Name = "userId", EmitDefaultValue = true)]
    public string UserId { get; set; }

    /// <summary>
    ///     Gets or Sets User
    /// </summary>
    [DataMember(Name = "user", EmitDefaultValue = false)]
    public NovaLabUser User { get; set; }

    /// <summary>
    ///     Gets or Sets DailyGoal
    /// </summary>
    [DataMember(Name = "dailyGoal", EmitDefaultValue = false)]
    public int DailyGoal { get; set; }

    /// <summary>
    ///     Gets or Sets CustomCssStyling
    /// </summary>
    [DataMember(Name = "customCssStyling", EmitDefaultValue = true)]
    public string CustomCssStyling { get; set; }

    /// <summary>
    ///     Returns true if TwitchFollowerGoal instances are equal
    /// </summary>
    /// <param name="input">Instance of TwitchFollowerGoal to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(TwitchFollowerGoal input) {
        if (input == null) {
            return false;
        }
        return
            (
                Id == input.Id ||
                Id != null &&
                Id.Equals(input.Id)
            ) &&
            (
                UserId == input.UserId ||
                UserId != null &&
                UserId.Equals(input.UserId)
            ) &&
            (
                User == input.User ||
                User != null &&
                User.Equals(input.User)
            ) &&
            (
                DailyGoal == input.DailyGoal ||
                DailyGoal.Equals(input.DailyGoal)
            ) &&
            (
                CustomCssStyling == input.CustomCssStyling ||
                CustomCssStyling != null &&
                CustomCssStyling.Equals(input.CustomCssStyling)
            );
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext) {
        // UserId (string) maxLength
        if (UserId != null && UserId.Length > 255) {
            yield return new ValidationResult("Invalid value for UserId, length must be less than 255.", new[] { "UserId" });
        }

        // CustomCssStyling (string) maxLength
        if (CustomCssStyling != null && CustomCssStyling.Length > 255) {
            yield return new ValidationResult("Invalid value for CustomCssStyling, length must be less than 255.", new[] { "CustomCssStyling" });
        }

    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString() {
        var sb = new StringBuilder();
        sb.Append("class TwitchFollowerGoal {\n");
        sb.Append("  Id: ").Append(Id).Append("\n");
        sb.Append("  UserId: ").Append(UserId).Append("\n");
        sb.Append("  User: ").Append(User).Append("\n");
        sb.Append("  DailyGoal: ").Append(DailyGoal).Append("\n");
        sb.Append("  CustomCssStyling: ").Append(CustomCssStyling).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson() => JsonConvert.SerializeObject(this, Formatting.Indented);

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input) => Equals(input as TwitchFollowerGoal);

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode() {
        unchecked// Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (Id != null) {
                hashCode = hashCode * 59 + Id.GetHashCode();
            }
            if (UserId != null) {
                hashCode = hashCode * 59 + UserId.GetHashCode();
            }
            if (User != null) {
                hashCode = hashCode * 59 + User.GetHashCode();
            }
            hashCode = hashCode * 59 + DailyGoal.GetHashCode();
            if (CustomCssStyling != null) {
                hashCode = hashCode * 59 + CustomCssStyling.GetHashCode();
            }
            return hashCode;
        }
    }
}
